create table users (
    id number generated by default as identity,
    name varchar(50) not null,
    email varchar(255) not null,
    password varchar(255),
    primary key(id)
);


insert into users(name,email,password) values ('Roberto Castillo','robertcastillo@gmail.com','clave'); 

commit;
select * from users;